RELATION_ARCHETYPES = (
    "NO_RELATION",
    "SYNONYM",
    "WORDPLAY",
    "PHRASE_COMPLETION",
    "TRIVIA_ENCYCLOPEDIC",
    "MORPHOLOGY",
)

NO_RELATION_IDX = 0
RELATION_ARCHETYPE_TO_IDX = {
    archetype: idx for idx, archetype in enumerate(RELATION_ARCHETYPES)
}
NUM_RELATION_ARCHETYPES = len(RELATION_ARCHETYPES)

